# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/gdiminin/Documents/ZURIGO/Python/HaSAPPy_GUI/filterSelection.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Filter(object):
    def setupUi(self, Filter):
        Filter.setObjectName(_fromUtf8("Filter"))
        Filter.resize(460, 220)
        Filter.setMinimumSize(QtCore.QSize(460, 220))
        Filter.setMaximumSize(QtCore.QSize(460, 220))
        self.buttonBox = QtGui.QDialogButtonBox(Filter)
        self.buttonBox.setGeometry(QtCore.QRect(130, 180, 321, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.selected = QtGui.QListWidget(Filter)
        self.selected.setGeometry(QtCore.QRect(340, 30, 111, 141))
        self.selected.setObjectName(_fromUtf8("selected"))
        self.label_4 = QtGui.QLabel(Filter)
        self.label_4.setGeometry(QtCore.QRect(340, 10, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_7 = QtGui.QLabel(Filter)
        self.label_7.setGeometry(QtCore.QRect(50, 10, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(Filter)
        self.label_8.setGeometry(QtCore.QRect(150, 10, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.line = QtGui.QFrame(Filter)
        self.line.setGeometry(QtCore.QRect(230, 0, 20, 241))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.layoutWidget = QtGui.QWidget(Filter)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 104, 148))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.sample = QtGui.QComboBox(self.layoutWidget)
        self.sample.setObjectName(_fromUtf8("sample"))
        self.verticalLayout.addWidget(self.sample)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.parameter = QtGui.QComboBox(self.layoutWidget)
        self.parameter.setObjectName(_fromUtf8("parameter"))
        self.verticalLayout.addWidget(self.parameter)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.function = QtGui.QComboBox(self.layoutWidget)
        self.function.setObjectName(_fromUtf8("function"))
        self.verticalLayout.addWidget(self.function)
        self.layoutWidget1 = QtGui.QWidget(Filter)
        self.layoutWidget1.setGeometry(QtCore.QRect(240, 30, 91, 134))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.add = QtGui.QPushButton(self.layoutWidget1)
        self.add.setObjectName(_fromUtf8("add"))
        self.verticalLayout_2.addWidget(self.add)
        self.up = QtGui.QPushButton(self.layoutWidget1)
        self.up.setObjectName(_fromUtf8("up"))
        self.verticalLayout_2.addWidget(self.up)
        self.down = QtGui.QPushButton(self.layoutWidget1)
        self.down.setObjectName(_fromUtf8("down"))
        self.verticalLayout_2.addWidget(self.down)
        self.remove = QtGui.QPushButton(self.layoutWidget1)
        self.remove.setObjectName(_fromUtf8("remove"))
        self.verticalLayout_2.addWidget(self.remove)
        self.layoutWidget2 = QtGui.QWidget(Filter)
        self.layoutWidget2.setGeometry(QtCore.QRect(120, 30, 123, 98))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_5 = QtGui.QLabel(self.layoutWidget2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.operation = QtGui.QComboBox(self.layoutWidget2)
        self.operation.setObjectName(_fromUtf8("operation"))
        self.operation.addItem(_fromUtf8(""))
        self.operation.addItem(_fromUtf8(""))
        self.operation.addItem(_fromUtf8(""))
        self.operation.addItem(_fromUtf8(""))
        self.operation.addItem(_fromUtf8(""))
        self.operation.addItem(_fromUtf8(""))
        self.operation.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.operation)
        self.label_6 = QtGui.QLabel(self.layoutWidget2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_3.addWidget(self.label_6)
        self.value = QtGui.QDoubleSpinBox(self.layoutWidget2)
        self.value.setObjectName(_fromUtf8("value"))
        self.verticalLayout_3.addWidget(self.value)

        self.retranslateUi(Filter)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Filter.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Filter.reject)
        QtCore.QMetaObject.connectSlotsByName(Filter)

    def retranslateUi(self, Filter):
        Filter.setWindowTitle(_translate("Filter", "Dialog", None))
        self.label_4.setText(_translate("Filter", "Selected Filters", None))
        self.label_7.setText(_translate("Filter", "Key", None))
        self.label_8.setText(_translate("Filter", "Filter", None))
        self.label.setText(_translate("Filter", "Sample", None))
        self.label_2.setText(_translate("Filter", "Parameter", None))
        self.label_3.setText(_translate("Filter", "Function", None))
        self.add.setText(_translate("Filter", "Add", None))
        self.up.setText(_translate("Filter", "Up", None))
        self.down.setText(_translate("Filter", "Down", None))
        self.remove.setText(_translate("Filter", "Remove", None))
        self.label_5.setText(_translate("Filter", "Operation", None))
        self.operation.setItemText(0, _translate("Filter", "-None-", None))
        self.operation.setItemText(1, _translate("Filter", "ascending", None))
        self.operation.setItemText(2, _translate("Filter", "descending", None))
        self.operation.setItemText(3, _translate("Filter", ">", None))
        self.operation.setItemText(4, _translate("Filter", ">=", None))
        self.operation.setItemText(5, _translate("Filter", "<", None))
        self.operation.setItemText(6, _translate("Filter", "<=", None))
        self.label_6.setText(_translate("Filter", "Value", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Filter = QtGui.QDialog()
    ui = Ui_Filter()
    ui.setupUi(Filter)
    Filter.show()
    sys.exit(app.exec_())

